name = "AIFF"
uuid = "1b604ab5-8734-4983-954d-ef9ae1cbea4b"
authors = ["amemiya"]
version = "0.1.0"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
